# This is an example rule. The original rule is using STARTS_WITH
# Which means it needs some work before we can use this
category: DATABASE
lookups:
  - entityTypes:
    - domain: INFRA
      type: AWSRDSDBCLUSTER
    - domain: INFRA
      type: AWSRDSDBINSTANCE
    tags:
      matchingMode: ANY
      predicates:
        - tagKeys: ["aws.endpoint", "aws.readerEndpoint", "aws.customEndpoints", "aws.rds.endpoint", "aws.rds.readerEndpoint", "aws.rds.customEndpoints"]
          field: endpoint
    onMatch:
     onMultipleMatches: RELATE_ALL
    onMiss:
      action: CREATE_UNINSTRUMENTED