relationships:
  - name: nodeExporterHostsApm
    version: 1
    origins:
      - APM Metrics
    conditions:
      - attribute: host.name
        present: yes
    relationship:
      expires: P1D
      relationshipType: HOSTS
      source:
        lookupGuid:
          candidateCategory: NODEEXPORTER
          fields:
            - field: nodename
              attribute: host.name
      target:
        extractGuid:
          attribute: entity.guid

