relationships:
  - name: apmProducesAwsMqQueue
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        regex: "^MessageBroker/instance/[^/]*\\.mq\\.[^/]*\\.amazonaws\\.com/[0-9]+/Queue/Named/[^/]*""
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        lookupGuid:
          candidateCategory: AWSMQQUEUE
          fields:
            - field: endpoint
              attribute: metricName__4              
            - field: port 
              attribute: metricName__5
