relationships:
  - name: apmApplicationCallsInfraMSSQLInstance
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: metricName
        # "datastore/instance/MSSQL/$host/$port"
        startsWith: "datastore/instance/MSSQL/"
        caseSensitive: false
    relationship:
      expires: P75M
      relationshipType: CALLS
      source:
        extractGuid:
          attribute: entity.guid
      target:
        buildGuid:
          account:
            lookup: yes
          domain:
            value: INFRA
          type:
            value: MSSQLINSTANCE
            valueInGuid: NA
          identifier:
            fragments:
              - value: "ms-instance:"
              - capture:
                attribute: metricName  
                # ex1: "datastore/instance/MSSQL/abc123.mydomain.local/1663" - keeps "abc123"
                # ex2: "datastore/instance/MSSQL/hostname/default"  - keeps "hostname"
                regex: "datastore/instance/MSSQL\/([^\\.\\/]+).*/.*"
                operations:
                  - operation: toLowerCase
            hashAlgorithm: FARM_HASH
