relationships:
  - name: extTeamToApmApplication
    version: "1"
    origins:
      - APM Metrics
    conditions:
      - attribute: nr.team
        present: true
    relationship:
      expires: P75M
      relationshipType: OWNS
      source:
        lookupGuid:
          candidateCategory: TEAM
          fields:
            - field: nr.team
              attribute: name
      target:
        extractGuid:
          attribute: entity.guid
