name: validate entity synthesis definitions
on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  validate:
    name: Validation
    runs-on: ubuntu-latest
    steps:
      - name: Show current directory
        run: pwd
      - name: Show directory content
        run: ls -la
      - name: Show current directory content recursively
        run: du
      - name: Show $GITHUB_WORKSPACE
        run: echo $GITHUB_WORKSPACE
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"
          path: "prcode"
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm --prefix validator install
      - name: Show current directory
        run: pwd
      - name: Show directory content
        run: ls -la
      - name: Show current directory content recursively 2
        run: du
      - name: Show directory content 2
        run: ls -la prcode
      - name: Validate definition
        run: npm --prefix validator run check
        env:
          PR_NUMBER: ${{ github.event.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Ensure sanitize was run
        # Runs the sanitize script and checks errors if the dashboards were not sanitized.
        # If the dashboards were sanitized, the git command will return 0 and the step will pass.
        run: npm --prefix validator run sanitize-dashboards &&  git diff-index --quiet HEAD -- entity-types/
